version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - mynetwork

  redis:
    image: redis
    container_name: redis-container
    ports:
      - '6379:6379'
    networks:
      - mynetwork

  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userauth
    ports:
      - '5432:5432'
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
    driver: local
